# Generated by Django 5.0.2 on 2024-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
