# Generated by Django 5.0.2 on 2024-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubApp', '0003_communitypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
